name: Kessoku Private CI
description: Post an authorized request to the server with `kessoku-private-ci`

inputs:
  auth:
    description: The API token in Basic format
    required: true
  endpoint:
    description: The API endpoint
    required: true
  payload:
    description: The payload of the request in JSON format
    required: true

runs:
  using: node20
  main: dist/index.js
