name: Deploy Website
description: Private Workflow

inputs:
  auth:
    description: In Basic format
    required: true
  endpoint:
    description: The API endpoint
    required: true
  github_run_id:
    description: "The id of the workflow run where the desired download artifact was uploaded from."
    required: true

runs:
  using: node20
  main: dist/index.js
